# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, feat, docs ]
  pull_request:
    branches: [ main, feat, docs ]

jobs:
  build:
    environment: test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: pnpm install

      - name: Build
        run: pnpm run build:package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dist
          path: ./
        
  download:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
    

